# Generated by Django 5.2.2 on 2025-06-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkindrive',
            name='time',
        ),
        migrations.AddField(
            model_name='walkindrive',
            name='end_time',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walkindrive',
            name='start_time',
            field=models.TimeField(default='17:00:00'),
            preserve_default=False,
        ),
    ]
