services:
  - type: web
    name: walkin-portal
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn jobportal.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: jobportal.settings
      - key: PYTHON_VERSION
        value: 3.11
